## Assignment 3: $k$ Nearest Neighbor

**Do two questions.**

`! git clone https://github.com/ds4e/knn`

In [1]:
! git clone https://github.com/ds4e/knn

Cloning into 'knn'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 63 (delta 22), reused 5 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (63/63), 23.08 MiB | 9.00 MiB/s, done.
Resolving deltas: 100% (22/22), done.


**Q0.**
1. What is the difference between regression and classification?
**Regression is used to predict a continuous quanity given observed variables, while classificiation uses variables to make an assessment of where something falls, categorically.**
2. What is a confusion table? What does it help us understand about a model's performance?
**When testing a model's performance in classification, we can use a confusion table to cross-tabulate the predicted and actual values, which shows how many true positives, false negatives, false positives, and true negatives the model is giving us based on the data we feed it.**
3. What does the SSE quantify about a particular model?
**For a linear regression model, the Sum of Squared Error can tell us how well the model fits the data, or how well it's performing based on data we have fed it.**
4. What are overfitting and underfitting?
**Underfitting is when you feed the model too little data, and thus it is unable to recognize patterns and use them to make predictions with new data. Overfitting, on the other hand, is when you feed the model too much data, and thus it is too complex and unable to perform well when given new data.**
5. Why does splitting the data into training and testing sets, and choosing $k$ by evaluating accuracy or SSE on the test set, improve model performance?
**We want to know how well a model will perform when given new data. Therefore, by saving some data as a testing set, we can train it based off our training set, then ask it to perform on our test set, and evaluate its performance based on how well it predicts the test set's data.**
6. With classification, we can report a class label as a prediction or a probability distribution over class labels. Please explain the strengths and weaknesses of each approach.
**Using a single class label is very simple, both in terms of clarity of understanding and comuptational efficiency. However, it is limited in showing the confidence of the model and misinterpretation. A probability distribution, on the other hand, allows us to make more involved decisions using the model's uncertainty, although it may be harder to get a read/intuitive understanding of.**

**Q1.** This question is a case study for $k$ nearest neighbor regression, using the `USA_cars_datasets.csv` data.

The target variable `y` is `price` and the features are `year` and `mileage`.

1. Load the `./data/USA_cars_datasets.csv`. Keep the following variables and drop the rest: `price`, `year`, `mileage`. Are there any `NA`'s to handle? Look at the head and dimensions of the data.
2. Maxmin normalize `year` and `mileage`.
3. Split the sample into ~80% for training and ~20% for evaluation.
4. Use the $k$NN algorithm and the training data to predict `price` using `year` and `mileage` for the test set for $k=3,10,25,50,100,300$. For each value of $k$, compute the mean squared error and print a scatterplot showing the test value plotted against the predicted value. What patterns do you notice as you increase $k$?
5. Determine the optimal $k$ for these data.
6. Describe what happened in the plots of predicted versus actual prices as $k$ varied, taking your answer into part 6 into account. (Hint: Use the words "underfitting" and "overfitting".)

**Q2.** This is a case study on $k$ nearest neighbor classification, using the `animals.csv` data.

The data consist of a label, `class`, taking integer values 1 to 7, the name of the species, `animal`, and 16 characteristics of the animal, including `hair`, `feathers`, `milk`, `eggs`, `airborne`, and so on.

1. Load the data. For each of the seven class labels, print the values in the class and get a sense of what is included in that group. Perform some other EDA: How big are the classes? How much variation is there in each of the features/covariates? Which variables do you think will best predict which class?
2. Split the data 50/50 into training and test/validation sets. (The smaller the data are, the more equal the split should be, in my experience: Otherwise, all of the members of one class end up in the training or test data, and the model falls apart.)
3. Using all of the variables, build a $k$-NN classifier. Explain how you select $k$.
4. Print a confusion table for the optimal model, comparing predicted and actual class label on the test set. How accurate it is? Can you interpret why mistakes are made across groups?
5. Use only `milk`, `aquatic`, and `airborne` to train a new $k$-NN classifier. Print your confusion table. Mine does not predict all of the classes, only a subset of them. To see the underlying probabilities, use `model.predict_proba(X_test.values)` to predict probabilities rather than labels for your `X_test` test data for your fitted `model`. Are all of the classes represented? Explain your results.

**Q3.** This question is a case study for $k$ nearest neighbor regression, using the `cars_env.csv` data.

The variables that go into the model are one more dimension to think about: We can use the train-test split approach to pick the variables that go into the model, not just the number of neighbors.

1. Load the data. We're going to use `footprint`, `baseline mpg`, `baseline price`, and `baseline sales`. Prepare some EDA results for these variables: describe tables, histograms/kernel density plots, scatterplots, etc. I renamed these variables to `footprint`, `mpg`, `price`, and `sales` to save time.
2. Maxmin normalize `footprint`, `mpg`, and `price`. These will be our features/covariates $X$. Our target/dependent/outcome variable $y$ will be sales. Does it make sense to normalize $y$?
3. Make a 30% train-test split of the data into 30% test/validation data and 70% training data.
4. Using all three covariates --- `footprint`, `mpg`, and `price` --- what's the best $k$ to use? What SSE is achieved on the test set? To answer these questions, evalute the sum of squared error on the test set for a reasonable range of values of $k$ (perhaps 2 to 150), and find the $k$ with the lowest SSE.
5. Do part 4 again, for each pair of variables: `footprint` and `mpg`, `footprint` and `price`, `mpg` and `price`.
6. Which set of variables from parts 4 and 5 does the best, in terms of minimizing SSE at the optimal choice of neighbors? Explain.

**Q4.** This is a case study on $k$ nearest neighbor classification, using the `land_mines.csv` data.

The data consists of a label, `mine_type`, taking integer values 1 to 5, and three properties of the mine, `voltage`, `height` and `soil`. We want to predict the kind of mine from data about it. Imagine working for the DOD or a humanitarian aid agency, trying to help people remove land mines more safely.

1. Load the data. Perform some EDA, summarizing the target label and the features.
2. Split the sample 50/50 into training and test/validation sets. (The smaller the data are, the more equal the split should be, in my experience: Otherwise, all of the members of one class end up in the training or test data, and the model falls apart.)
3. Build a $k$-NN classifier. Explain how you select $k$.
4. Print a confusion table for the optimal model, comparing predicted and actual class label on the test set. How accurate is it? Where is performance more or less accurate?
5. Notice that you can have a lot of accurate predictions for a given type of mine, but still make a lot of mistakes. Please explain how you'd advise someone to actually use this predictive model in practice, given the errors that it tends to make.

In [23]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsRegressor

#1
df = pd.read_csv('/content/knn/data/land_mines.csv')
print(df.describe())
print(df['mine_type'].value_counts())
print(df[['voltage', 'height', 'soil']].corr())

#2
# Create target variable vector and feature matrix
y = df['mine_type']
X = df.loc[:, ['voltage', 'height', 'soil']]

# Normalize the feature matrix using MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)  # Normalize features to the 0-1 range

# Split the dataset 50/50 into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.5,  # 50/50 split
                                                    random_state=65)  # For reproducibility

#3
k_bar = 50  # Number of k's to try
SSE = []  # To store SSE for test set
SSE_on_train = []  # To store SSE for training set

for k in range(k_bar):
    model = KNeighborsRegressor(n_neighbors=k+1)  # Create the k-NN model with current k
    fitted_model = model.fit(X_train, y_train)  # Train the model on the training data
    y_hat_test = fitted_model.predict(X_test)  # Predict values for the test set
    SSE.append(np.sum((y_test - y_hat_test)**2))  # Calculate and store SSE for the test set
    y_hat_train = fitted_model.predict(X_train)  # Predict values for the training set
    SSE_on_train.append(np.sum((y_train - y_hat_train)**2))  # Calculate and store SSE for training set

# Find the minimum SSE on the test set
SSE_min = np.min(SSE)  # Get the lowest SSE value
min_index = np.where(SSE == SSE_min)  # Get the index of the minimum SSE
k_star = min_index[0] + 1  # Get the optimal k (index + 1 as k starts from 1, not 0)
print(f"\nThe optimal value of k is: {k_star[0]}, which we found by calculating the minimum SSE from our training data to our test data.")

#4
final_model = KNeighborsClassifier(n_neighbors=k_star[0])  # Train the model with the best k
final_model.fit(X_train, y_train)

# Predict on the test set
y_pred = final_model.predict(X_test)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

# Print the confusion matrix and accuracy
print("\nConfusion Matrix:")
print(cm)
print(f"Accuracy: {accuracy:.2f}\nThe performance is not very accuarate--definitely not as accurate as we would like for a landmine checker. ")
print('It looks like the model is better at predicting type one and type 2 landmines, and not good at predicting the others.')

#5
print('If this predictive model were actually used in practice, which it should not, I would tell them Type 2 mines are the only ones that can be reasonably predicted by this model.')

          voltage      height        soil   mine_type
count  338.000000  338.000000  338.000000  338.000000
mean     0.430634    0.508876    0.503550    2.952663
std      0.195819    0.306043    0.344244    1.419703
min      0.197734    0.000000    0.000000    1.000000
25%      0.309737    0.272727    0.200000    2.000000
50%      0.359516    0.545455    0.600000    3.000000
75%      0.482628    0.727273    0.800000    4.000000
max      0.999999    1.000000    1.000000    5.000000
mine_type
1    71
2    70
3    66
4    66
5    65
Name: count, dtype: int64
          voltage    height      soil
voltage  1.000000 -0.377523  0.070673
height  -0.377523  1.000000 -0.006957
soil     0.070673 -0.006957  1.000000

The optimal value of k is: 11, which we found by calculating the minimum SSE from our training data to our test data.

Confusion Matrix:
[[26  0  3  2  3]
 [ 0 30  6  0  2]
 [ 3  2 10  2 13]
 [14  0 13  4  7]
 [11  0 11  2  5]]
Accuracy: 0.44
The performance is not very accuarate--def

**Q5.** This question is a case study for $k$ nearest neighbor regression, using the `heart_failure_clinical_records_dataset.csv` data.

The data for the question include:

- age: age of the patient (years)
- anaemia: decrease of red blood cells or hemoglobin (boolean)
- high blood pressure: if the patient has hypertension (boolean)
- creatinine phosphokinase (CPK): level of the CPK enzyme in the blood (mcg/L)
- diabetes: if the patient has diabetes (boolean)
- ejection fraction: percentage of blood leaving the heart at each contraction (percentage)
- platelets: platelets in the blood (kiloplatelets/mL)
- sex: woman or man (binary)
- serum creatinine: level of serum creatinine in the blood (mg/dL)
- serum sodium: level of serum sodium in the blood (mEq/L)
- smoking: if the patient smokes or not (boolean)
- time: follow-up period (days)
- death event: if the patient deceased during the follow-up period (boolean)

1. Load the `./data/heart_failure_clinical_records_dataset.csv`. Are there any `NA`'s to handle? use `.drop()` to remove `time` from the dataframe.
2. Make a correlation matrix. What variables are strongly associated with a death event?
3. For the dummy variables `anaemia`, `diabetes`, `high_blood_pressure`, `sex`, and `smoking`, compute a summary table of `DEATH_EVENT` grouped by the variable. For which variables does a higher proportion of the population die when the variable takes the value 1 rather than 0?
4. On the basis of your answers from 2 and 3, build a matrix $X$ of the variables you think are most predictive of a death, and a variable $y$ equal to `DEATH_EVENT`.
5. Maxmin normalize all of the variables in `X`.
6. Split the sample into ~80% for training and ~20% for evaluation. (Try to use the same train/test split for the whole question, so that you're comparing apples to apples in the questions below.).
7. Determine the optimal number of neighbors for a $k$NN regression for the variables you selected.
8. OK, do steps 5 through 7 again, but use all of the variables (except `time`). Which model has a lower Sum of Squared Error? Which would you prefer to use in practice, if you had to predict `DEATH_EVENT`s? If you play with the selection of variables, how much does the SSE change for your fitted model on the test data? Are more variables always better? Explain your findings.

**Q6.** This is a case study on $k$ nearest neighbor regression and imputation, using the `airbnb_hw.csv` data.

There are 30,478 observations, but only 22,155 ratings. We're going to build a kNN regressor to impute missing values. This is a common task, and illustrates one way you can use kNN in the future even when you have more advanced models available.

1. Load the `airbnb_hw.csv` data with Pandas. We're only going to use `Review Scores Rating`, `Price`, and `Beds`, so use `.loc` to reduce the dataframe to those variables.
2. Set use `.isnull()` to select the subset of the dataframe with missing review values. Set those aside in a different dataframe. We'll make predictions about them later.
3. Use `df = df.dropna(axis = 0, how = 'any')` to eliminate any observations with missing values/NA's from the dataframe.
4. For the complete cases, create a $k$-NN model that uses the variables `Price` and `Beds` to predict `Review Scores Rating`. How do you choose $k$? (Hint: Train/test split, iterate over reasonable values of $k$ and find a value that minimizes SSE on the test split using predictions from the training set.)
5. Predict the missing ratings.
6. Do a kernel density plot of the training ratings and the predicted missing ratings. Do they look similar or not? Explain why.